name: Release

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version"
    outputs:
      version: ${{ steps.cz.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.11

      - name: Config Git User
        run: |
          git config --local user.email "$GIT_USER_EMAIL"
          git config --local user.name "$GIT_USER_NAME"
          git config --local pull.ff only

      - id: cz
        name: Create bump and changelog
        run: |
          python -m pip install -U commitizen
          cz bump --changelog --yes
          export REV=`cz version --project`
          echo "version=$REV" >> $GITHUB_OUTPUT

      - name: Push changes
        uses: Woile/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          tags: true
          branch: main

      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

  npm_publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs:
      - bump_version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: main

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          tag: ${{ needs.bump_version.outputs.version }}
          access: public
          strategy: upgrade

  release:
    name: Release version
    runs-on: ubuntu-latest
    needs:
      - bump_version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: main

      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          automatic_release_tag: ${{ needs.bump_version.outputs.version }}
          prerelease: false
